bot:
  account: 123456789
  password: 123456789

modules:
  daredemo_suki:
    is_enabled: true
    config_path: "./dd.yaml"

  shell:
    is_enabled: true
    config_path: "./shell.yaml"

  bili:
    is_enabled: true
    config_path: "./bili.yaml"

  naive_chatbot:
    is_enabled: true
    config_path: "./naive_chatbot.yaml"

  diary:
    is_enabled: true
    config_path: "./diary.yaml"
