// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: protos/predictor.proto

package predictor

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type PredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg               *string  `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	NPrediction       *int64   `protobuf:"varint,2,opt,name=n_prediction,json=nPrediction,def=5" json:"n_prediction,omitempty"`
	TimeOffsetSeconds *int64   `protobuf:"varint,3,opt,name=time_offset_seconds,json=timeOffsetSeconds,def=300" json:"time_offset_seconds,omitempty"`
	SimCutoff         *float32 `protobuf:"fixed32,4,opt,name=sim_cutoff,json=simCutoff,def=0" json:"sim_cutoff,omitempty"`
}

// Default values for PredictRequest fields.
const (
	Default_PredictRequest_NPrediction       = int64(5)
	Default_PredictRequest_TimeOffsetSeconds = int64(300)
	Default_PredictRequest_SimCutoff         = float32(0)
)

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_predictor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_predictor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_protos_predictor_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

func (x *PredictRequest) GetNPrediction() int64 {
	if x != nil && x.NPrediction != nil {
		return *x.NPrediction
	}
	return Default_PredictRequest_NPrediction
}

func (x *PredictRequest) GetTimeOffsetSeconds() int64 {
	if x != nil && x.TimeOffsetSeconds != nil {
		return *x.TimeOffsetSeconds
	}
	return Default_PredictRequest_TimeOffsetSeconds
}

func (x *PredictRequest) GetSimCutoff() float32 {
	if x != nil && x.SimCutoff != nil {
		return *x.SimCutoff
	}
	return Default_PredictRequest_SimCutoff
}

// The response message containing the greetings
type PredictReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*PredictReply_PredictReplyElem `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (x *PredictReply) Reset() {
	*x = PredictReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_predictor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictReply) ProtoMessage() {}

func (x *PredictReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_predictor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictReply.ProtoReflect.Descriptor instead.
func (*PredictReply) Descriptor() ([]byte, []int) {
	return file_protos_predictor_proto_rawDescGZIP(), []int{1}
}

func (x *PredictReply) GetResult() []*PredictReply_PredictReplyElem {
	if x != nil {
		return x.Result
	}
	return nil
}

type PredictReply_PredictReplyElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *string  `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	Sim *float32 `protobuf:"fixed32,2,req,name=sim" json:"sim,omitempty"`
}

func (x *PredictReply_PredictReplyElem) Reset() {
	*x = PredictReply_PredictReplyElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_predictor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictReply_PredictReplyElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictReply_PredictReplyElem) ProtoMessage() {}

func (x *PredictReply_PredictReplyElem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_predictor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictReply_PredictReplyElem.ProtoReflect.Descriptor instead.
func (*PredictReply_PredictReplyElem) Descriptor() ([]byte, []int) {
	return file_protos_predictor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PredictReply_PredictReplyElem) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

func (x *PredictReply_PredictReplyElem) GetSim() float32 {
	if x != nil && x.Sim != nil {
		return *x.Sim
	}
	return 0
}

var File_protos_predictor_proto protoreflect.FileDescriptor

var file_protos_predictor_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x24, 0x0a,
	0x0c, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x3a, 0x01, 0x35, 0x52, 0x0b, 0x6e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x3a, 0x03, 0x33, 0x30, 0x30, 0x52, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x5f,
	0x63, 0x75, 0x74, 0x6f, 0x66, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01, 0x30, 0x52,
	0x09, 0x73, 0x69, 0x6d, 0x43, 0x75, 0x74, 0x6f, 0x66, 0x66, 0x22, 0x7e, 0x0a, 0x0c, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x1a, 0x36, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x6d, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x73, 0x69, 0x6d, 0x32, 0x3f, 0x0a, 0x0d, 0x43, 0x68,
	0x61, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x0a, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
}

var (
	file_protos_predictor_proto_rawDescOnce sync.Once
	file_protos_predictor_proto_rawDescData = file_protos_predictor_proto_rawDesc
)

func file_protos_predictor_proto_rawDescGZIP() []byte {
	file_protos_predictor_proto_rawDescOnce.Do(func() {
		file_protos_predictor_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_predictor_proto_rawDescData)
	})
	return file_protos_predictor_proto_rawDescData
}

var file_protos_predictor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_predictor_proto_goTypes = []interface{}{
	(*PredictRequest)(nil),                // 0: PredictRequest
	(*PredictReply)(nil),                  // 1: PredictReply
	(*PredictReply_PredictReplyElem)(nil), // 2: PredictReply.PredictReplyElem
}
var file_protos_predictor_proto_depIdxs = []int32{
	2, // 0: PredictReply.result:type_name -> PredictReply.PredictReplyElem
	0, // 1: ChatPredictor.PredictOne:input_type -> PredictRequest
	1, // 2: ChatPredictor.PredictOne:output_type -> PredictReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_predictor_proto_init() }
func file_protos_predictor_proto_init() {
	if File_protos_predictor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_predictor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_predictor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_predictor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictReply_PredictReplyElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_predictor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_predictor_proto_goTypes,
		DependencyIndexes: file_protos_predictor_proto_depIdxs,
		MessageInfos:      file_protos_predictor_proto_msgTypes,
	}.Build()
	File_protos_predictor_proto = out.File
	file_protos_predictor_proto_rawDesc = nil
	file_protos_predictor_proto_goTypes = nil
	file_protos_predictor_proto_depIdxs = nil
}
